import type { Vehicle } from './types';

export const vehiclesMock: Vehicle[] = [
  {
    id: '1',
    brand: 'Toyota',
    model: 'Corolla',
    year: 2022,
    price: 125000,
    location: 'São Paulo, SP',
    image: 'https://placehold.co/400x280?text=Toyota+Corolla',
    description: 'Toyota Corolla 2022 em excelente estado. Único dono, revisões em dia na concessionária.',
    mileage: 32000,
    color: 'Prata',
    transmission: 'Automático',
    fuel: 'Flex',
    gallery: [
      'https://placehold.co/800x500?text=Corolla+1',
      'https://placehold.co/800x500?text=Corolla+2',
      'https://placehold.co/800x500?text=Corolla+3',
    ],
  },
  {
    id: '2',
    brand: 'Honda',
    model: 'Civic',
    year: 2023,
    price: 145000,
    location: 'Rio de Janeiro, RJ',
    image: 'https://placehold.co/400x280?text=Honda+Civic',
    description: 'Honda Civic 2023 com pacote de tecnologia. Apenas 10.000 km rodados.',
    mileage: 10000,
    color: 'Branco',
    transmission: 'Automático',
    fuel: 'Flex',
    gallery: [
      'https://placehold.co/800x500?text=Civic+1',
      'https://placehold.co/800x500?text=Civic+2',
    ],
  },
  {
    id: '3',
    brand: 'Volkswagen',
    model: 'Golf GTI',
    year: 2021,
    price: 175000,
    location: 'Curitiba, PR',
    image: 'https://placehold.co/400x280?text=VW+Golf+GTI',
    description: 'Golf GTI 2021 esportivo e completo. Veículo em perfeito estado de conservação.',
    mileage: 45000,
    color: 'Cinza',
    transmission: 'Automático',
    fuel: 'Gasolina',
    gallery: [
      'https://placehold.co/800x500?text=Golf+1',
      'https://placehold.co/800x500?text=Golf+2',
      'https://placehold.co/800x500?text=Golf+3',
    ],
  },
  {
    id: '4',
    brand: 'Hyundai',
    model: 'HB20',
    year: 2023,
    price: 72000,
    location: 'Belo Horizonte, MG',
    image: 'https://placehold.co/400x280?text=Hyundai+HB20',
    description: 'HB20 2023 zerado, primeiro emplacamento. Ideal para cidade.',
    mileage: 5000,
    color: 'Vermelho',
    transmission: 'Manual',
    fuel: 'Flex',
    gallery: [
      'https://placehold.co/800x500?text=HB20+1',
    ],
  },
  {
    id: '5',
    brand: 'Jeep',
    model: 'Compass',
    year: 2022,
    price: 195000,
    location: 'Porto Alegre, RS',
    image: 'https://placehold.co/400x280?text=Jeep+Compass',
    description: 'Jeep Compass 2022 Limited com teto panorâmico. Único dono, impecável.',
    mileage: 28000,
    color: 'Preto',
    transmission: 'Automático',
    fuel: 'Diesel',
    gallery: [
      'https://placehold.co/800x500?text=Compass+1',
      'https://placehold.co/800x500?text=Compass+2',
    ],
  },
  {
    id: '6',
    brand: 'Fiat',
    model: 'Pulse',
    year: 2023,
    price: 105000,
    location: 'Salvador, BA',
    image: 'https://placehold.co/400x280?text=Fiat+Pulse',
    description: 'Fiat Pulse 2023 Impetus turbo. Carro novo, poucos meses de uso.',
    mileage: 8000,
    color: 'Azul',
    transmission: 'Automático',
    fuel: 'Flex',
    gallery: [
      'https://placehold.co/800x500?text=Pulse+1',
      'https://placehold.co/800x500?text=Pulse+2',
    ],
  },
];
